# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Testing' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod "PayPal-iOS-SDK", "~> 2.16.3"
  # Pods for Testing

  target 'TestingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

